export const VER_CONTADOR = 'VER_CONTADOR'
export const VER_CONTADOR_EXITO = 'VER_CONTADOR_EXITO'
export const VER_CONTADOR_ERROR = 'VER_CONTADOR_ERROR'

export const VER_CREDITOS_NUEVOS = 'VER_CREDITOS'
export const VER_CREDITOS_NUEVOS_EXITO = 'VER_CREDITOS_EXITO'
export const VER_CREDITOS_NUEVOS_ERROR = 'VER_CREDITOS_ERROR'

export const OBTENER_CREDITO_EDITAR = 'OBTENER_CREDITO_EDITAR';
export const COMENZAR_EDICION_CREDITO = 'COMENZAR_EDICION_CREDITO';
export const CREDITO_EDITADO_EXITO = 'CREDITO_EDITADO_EXITO';
export const CREDITO_EDITADO_ERROR = 'CREDITO_EDITADO_ERROR';

export const EDITAR_CONTADOR_EXITO = 'EDITAR_CONTADOR_EXITO';
export const OBTENER_CONTADOR_EDITAR = 'OBTENER_CONTADOR_EDITAR';

export const VER_FIRMA = 'VER_FIRMA'

