export const VER_CONTADOR = "VER_CONTADOR";
export const VER_CONTADOR_EXITO = "VER_CONTADOR_EXITO";
export const VER_CONTADOR_ERROR = "VER_CONTADOR_ERROR";

export const VER_CREDITOS_NUEVOS = "VER_CREDITOS";
export const VER_CREDITOS_NUEVOS_EXITO = "VER_CREDITOS_EXITO";
export const VER_CREDITOS_NUEVOS_ERROR = "VER_CREDITOS_ERROR";

export const OBTENER_CREDITO_EDITAR = "OBTENER_CREDITO_EDITAR";
export const COMENZAR_EDICION_CREDITO = "COMENZAR_EDICION_CREDITO";
export const CREDITO_EDITADO_EXITO = "CREDITO_EDITADO_EXITO";
export const CREDITO_EDITADO_ERROR = "CREDITO_EDITADO_ERROR";

export const EDITAR_CONTADOR_EXITO = "EDITAR_CONTADOR_EXITO";
export const OBTENER_CONTADOR_EDITAR = "OBTENER_CONTADOR_EDITAR";

export const VER_FIRMA = "VER_FIRMA";

export const VER_CLIENTES = "VER_CLIENTES";
export const VER_CLIENTES_EXITO = "VER_CLIENTES_EXITO";
export const VER_CLIENTES_ERROR = "VER_CLIENTES_ERROR";
export const OBTENER_CLIENTE_EDITAR = "OBTENER_CLIENTE_EDITAR";
export const COMENZAR_EDICION_CLIENTE = "COMENZAR_EDICION_CLIENTE";
export const CLIENTE_EDITADO_EXITO = "CLIENTE_EDITADO_EXITO";
export const CLIENTE_EDITADO_ERROR = "CLIENTE_EDITADO_ERROR";
export const EDICION_CLIENTE_EXITO = "EDICION_CLIENTE_EXITO";

export const CREDITOS_GENERAL = "CREDITOS_GENERAL";
export const CREDITOS_GENERAL_EXITO = "CREDITOS_GENERAL_ERROR";
export const CREDITOS_GENERAL_ERROR = "CREDITOS_GENERAL_EXITO";

export const COMPROMISOS_GENERAL = "COMPROMISOS_GENERAL";
export const COMPROMISOS_GENERAL_EXITO = "COMPROMISOS_GENERAL_EXITO";
export const COMPROMISOS_GENERAL_ERROR = "COMPROMISOS_GENERAL_ERROR";

export const CREAR_COMPROMISO = "CREAR_COMPROMISO";
export const CREAR_COMPROMISO_EXITO = "CREAR_COMPROMISO_EXITO";
export const CREAR_COMPROMISO_ERROR = "CREAR_COMPROMISO_ERROR";

export const CARGA_COMPROMISO_PARTICULAR = "CARGA_COMPROMISO_PARTICULAR";
export const COMPROMISO_PARTICULAR_EXITO = "COMPROMISO_PARTICULAR_EXITO";
export const COMPROMISO_PARTICULAR_ERROR = "COMPROMISO_PARTICULAR_ERROR";
